name: geopandas_docs
channels:
- conda-forge
dependencies:
- pandas
- shapely
- geos=3.4.2
- fiona
- pyproj
- rtree
- six
- geopy
- matplotlib
- descartes
- pysal
- sphinx
- sphinx_rtd_theme
- ipython=4.0.1
